### ISSUE TITLE
The merge_gdf does not work

### ISSUE THREAD

**Issue by diesseh** [maawoo/gedixr#19]
>>> gdf_l2a = extract_data(directory=gedi_dir, gedi_product='L2A', subset_vector=vec_path)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 762/762 [12:21:50<00:00, 58.41s/it]
WARNING: 5 errors occurred during the extraction process. Please check the log file!
>>> gdf_l2b = extract_data(directory=gedi_dir, gedi_product='L2B', subset_vector=vec_path)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 381/381 [3:30:39<00:00, 33.18s/it]
WARNING: 3 errors occurred during the extraction process. Please check the log file!
>>> gdf = merge_gdf(gdf_l2a=gdf_l2a, gdf_l2b=gdf_l2b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\diess\anaconda3\envs\gedixr_env\Lib\site-packages\gedixr\xr.py", line 82, in merge_gdf
    gdf_l2a = gdf_l2a.loc[:, ['rh98', 'geometry']]
              ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'loc'

**Comment by maawoo** [comment]
Hi @diesseh,
this issue is also a result of missing or misleading documentation, which I need to update soon. Sorry for the inconvenience!

When you use `extract_data` with the `subset_vector`-parameter, it will return a nested dictionary like this: 

```python
{'<Vector Basename>': 
    {'geo': shapely.Polygon,
     'gdf': geopandas.GeoDataFrame}
}
```

So let's say your input vector file is named `'area_of_interest.geojson'`. The basename of the file will be used as an identifying key to store another dictionary with the following keys:  
- `'geo'` to keep information about the polygon used to subset the data and...
- `'gdf'` with the extracted data as a GeoDataFrame. 

That means you can access the GeoDataFrames with `gdf_l2a['area_of_interest']['gdf']` and need to adjust the example that failed for you:
```python
 gdf = merge_gdf(gdf_l2a=gdf_l2a['area_of_interest']['gdf'], gdf_l2b=gdf_l2b['area_of_interest']['gdf'])
```

**Comment by maawoo** [comment]
Just be aware that merging in this way only really makes sense if both GeoDataFrames, with the L2A and L2B data respectively, contain data of exactly the same sample points / shots. If this is not the case, the function will print out a warning and you should make sure that the merged GeoDataFrame contains the data you expect.
